name: devel
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Cache Docker layers
        uses: mattes/cached-docker-build-action@v1
        with:
          args: "-t joseluisq/rust-linux-darwin-builder:latest -f Dockerfile ."
          cache_key: "${{ hashFiles('**/lockfiles') }}"
      -
        name: Test cross-compile
        uses: addnab/docker-run-action@v1
        with:
          image: joseluisq/rust-linux-darwin-builder:latest
          options: -v ${{ github.workspace }}:/root/src
          shell: bash
          run: |
            make test-ci
